import TemptingButton from "@/components/TemptingButton";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import Link from "next/link";

import "./globals.css";

const inter = Inter({ subsets: ["latin"] });
export const metadata: Metadata = {
  title: "small Zhao Game life Blog",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <nav>
          <ul>
            <li>
              <Link href="/">首页</Link>
            </li>
            <li>
              <Link href="/blog-home">BLOG</Link>
            </li>
            <li>
              <Link href="/contact">坚硬下的柔软需要被治愈</Link>
            </li>
          </ul>
        </nav>
        <TemptingButton />

        {children}
      </body>
    </html>
  );
}
