import Navbar from "@/components/Navbar";
import TemptingButton from "@/components/TemptingButton";
import type { Metadata } from "next";

import { Inter } from "next/font/google";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });
export const metadata: Metadata = {
  title: "small Zhao Game life Blog",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <div className="bg-white bg-opacity-5 w-70vw h-screen w-3/5 absolute top-1/2 left-1/2 transform -translate-x-1/2 -translate-y-1/2"></div>
        <div className="flex flex-1 justify-end md:justify-center">
          <Navbar />
        </div>
        <TemptingButton />
        {children}
      </body>
    </html>
  );
}
