export type IconProps = React.SVGAttributes<SVGElement>;
export { SparkleIcon } from "./icons/SparkleIcon";
export { UserSecurityIcon } from "./icons/UserSecurityIcon";
export { BilibiliIcon } from "./icons/BilibiliIcon";
export { AtomIcon } from "./icons/AtomIcon";
export { GitHubIcon } from "./icons/GitHubIcon";
export { MailIcon } from "./icons/MailIcon";
export { TelegramIcon } from "./icons/TelegramIcon";
export { TwitterIcon } from "./icons/TwitterIcon";
export { YouTubeIcon } from "./icons/YouTubeIcon";
